networks:
  default:
    external: true
    name: n8n_default

services:
  nextjs:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SITE_URL=${SITE_URL:-https://nanonomera.ru}
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=${SITE_URL:-https://nanonomera.ru}
      - SITE_URL=${SITE_URL:-https://nanonomera.ru}
    labels:
      - traefik.enable=true
      - traefik.http.routers.nanonomera.rule=Host(`nanonomera.ru`) || Host(`www.nanonomera.ru`)
      - traefik.http.routers.nanonomera.tls=true
      - traefik.http.routers.nanonomera.entrypoints=web,websecure
      - traefik.http.routers.nanonomera.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.nanonomera.headers.SSLRedirect=true
      - traefik.http.middlewares.nanonomera.headers.STSSeconds=315360000
      - traefik.http.middlewares.nanonomera.headers.browserXSSFilter=true
      - traefik.http.middlewares.nanonomera.headers.contentTypeNosniff=true
      - traefik.http.middlewares.nanonomera.headers.forceSTSHeader=true
      - traefik.http.middlewares.nanonomera.headers.SSLHost=nanonomera.ru
      - traefik.http.middlewares.nanonomera.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.nanonomera.headers.STSPreload=true
      - traefik.http.routers.nanonomera.middlewares=nanonomera@docker
      - traefik.http.services.nanonomera.loadbalancer.server.port=3000
    networks:
      - default
